# Generated by Django 4.2.7 on 2025-08-03 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferView",
            fields=[],
            options={
                "verbose_name": "Vista de Servicio",
                "verbose_name_plural": "Vista de Servicios",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("travels.transfer",),
        ),
        migrations.AlterModelOptions(
            name="code",
            options={"verbose_name": "VIP", "verbose_name_plural": "VIPs"},
        ),
        migrations.AlterModelOptions(
            name="transfer",
            options={"verbose_name": "Servicio", "verbose_name_plural": "Servicios"},
        ),
    ]
