# Generated by Django 4.2.7 on 2025-08-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travels", "0002_transferview_alter_code_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transfer",
            name="hour",
            field=models.TimeField(),
        ),
    ]
