# Generated by Django 4.2.7 on 2025-08-04 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travels", "0003_alter_transfer_hour"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TransferView",
        ),
        migrations.CreateModel(
            name="TransferDetail",
            fields=[],
            options={
                "verbose_name": "Vista de Servicio",
                "verbose_name_plural": "Vista de Servicios",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("travels.transfer",),
        ),
    ]
