# Generated by Django 4.2.7 on 2025-08-04 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("travels", "0005_location_transfertype_vehicletype_zone_pricing_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricing",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="travels.vehicletype"
            ),
        ),
    ]
