# Generated by Django 4.2.7 on 2025-08-04 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travels", "0006_alter_pricing_vehicle"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transfertype",
            options={
                "verbose_name": "Tipo de Servicio",
                "verbose_name_plural": "Tipos de Servicios",
            },
        ),
    ]
