# Generated by Django 4.2.7 on 2025-08-05 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0007_alter_transfertype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferdetail',
            options={'verbose_name': 'Detalle de Servicio', 'verbose_name_plural': 'Detalles de Servicios'},
        ),
    ]
