# Generated by Django 4.2.7 on 2025-08-05 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0008_alter_transferdetail_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Code',
            new_name='VipCode',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='code',
            new_name='vip_code',
        ),
    ]
