# Generated by Django 4.2.7 on 2025-08-05 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0010_remove_vehicle_type_vehicle_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='zone',
        ),
        migrations.AddField(
            model_name='location',
            name='zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travels.zone'),
            preserve_default=False,
        ),
    ]
