# Generated by Django 4.2.7 on 2025-08-05 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0011_remove_pricing_zone_location_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='place',
        ),
        migrations.AddField(
            model_name='transfer',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travels.location'),
            preserve_default=False,
        ),
    ]
