# Generated by Django 4.2.7 on 2025-08-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0012_remove_transfer_place_transfer_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='fee',
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('name', 'zone')},
        ),
    ]
