# Generated by Django 4.2.7 on 2025-08-06 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0013_remove_vehicle_fee_alter_zone_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransferDetail',
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Ventas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('travels.transfer',),
        ),
    ]
