# Generated by Django 4.2.7 on 2025-08-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0014_delete_transferdetail_saledetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='transfertype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vipcode',
            name='value',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
