# Generated by Django 4.2.7 on 2025-08-08 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("travels", "0015_alter_location_name_alter_transfertype_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Correo"),
        ),
        migrations.AlterField(
            model_name="client",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="Apellido"),
        ),
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(max_length=15, verbose_name="Teléfono"),
        ),
        migrations.AlterField(
            model_name="client",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de actualización"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="location",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de actualización"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="travels.zone",
                verbose_name="Zona",
            ),
        ),
        migrations.AlterField(
            model_name="pricing",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="pricing",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="travels.location",
                verbose_name="Ubicación",
            ),
        ),
        migrations.AlterField(
            model_name="pricing",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Precio"
            ),
        ),
        migrations.AlterField(
            model_name="pricing",
            name="transfer_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="travels.transfertype",
                verbose_name="Tipo de Servicio",
            ),
        ),
        migrations.AlterField(
            model_name="pricing",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de actualización"
            ),
        ),
        migrations.AlterField(
            model_name="pricing",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="travels.vehicle",
                verbose_name="Vehículo",
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="travels.client",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="passengers",
            field=models.IntegerField(verbose_name="Pasajeros"),
        ),
        migrations.AlterField(
            model_name="sale",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de actualización"
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="travels.vehicle",
                verbose_name="Vehículo",
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="vip_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="travels.vipcode",
                verbose_name="VIP",
            ),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Fecha"),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="hour",
            field=models.TimeField(verbose_name="Hora"),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="travels.location",
                verbose_name="Ubicación",
            ),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="sale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="travels.sale",
                verbose_name="Venta",
            ),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="travels.transfertype",
                verbose_name="Tipo de Servicio",
            ),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de actualización"
            ),
        ),
        migrations.AlterField(
            model_name="transfertype",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="transfertype",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="transfertype",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de actualización"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de actualización"
            ),
        ),
        migrations.AlterField(
            model_name="vipcode",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
        migrations.AlterField(
            model_name="vipcode",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="vipcode",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de actualización"
            ),
        ),
        migrations.AlterField(
            model_name="vipcode",
            name="value",
            field=models.CharField(max_length=10, unique=True, verbose_name="Código"),
        ),
        migrations.AlterField(
            model_name="zone",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="zone",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de actualización"
            ),
        ),
    ]
