# Generated by Django 4.2.7 on 2025-08-08 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0016_alter_client_created_at_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='vip_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.vipcode', verbose_name='Código VIP'),
        ),
    ]
