# Generated by Django 4.2.7 on 2025-08-08 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travels", "0016_alter_client_created_at_alter_client_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transfer",
            options={
                "verbose_name": "Transportación",
                "verbose_name_plural": "Transportaciones",
            },
        ),
        migrations.AlterModelOptions(
            name="transfertype",
            options={
                "verbose_name": "Tipo de Transportación",
                "verbose_name_plural": "Tipos de Transportación",
            },
        ),
    ]
