# Generated by Django 4.2.7 on 2025-08-08 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travels", "0017_alter_transfer_options_alter_transfertype_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TransferType",
            new_name="ServiceType",
        ),
    ]
