# Generated by Django 4.2.7 on 2025-08-08 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("travels", "0018_rename_transfertype_servicetype"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="service_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="travels.servicetype",
                verbose_name="Tipo de Servicio",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transfer",
            name="type",
            field=models.CharField(
                choices=[("Departure", "Departure"), ("Arrival", "Arrival")],
                default="Departure",
                max_length=100,
            ),
        ),
    ]
