# Generated by Django 4.2.7 on 2025-08-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travels", "0019_sale_service_type_alter_transfer_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicetype",
            options={
                "verbose_name": "Tipo de Servicio",
                "verbose_name_plural": "Tipos de Servicios",
            },
        ),
        migrations.AddField(
            model_name="transfer",
            name="airline",
            field=models.CharField(default=1, max_length=100, verbose_name="Aerolínea"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transfer",
            name="flight_number",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Número de Vuelo"
            ),
            preserve_default=False,
        ),
    ]
