# Generated by Django 4.2.7 on 2025-08-11 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0017_alter_sale_vip_code'),
        ('travels', '0020_alter_servicetype_options_transfer_airline_and_more'),
    ]

    operations = [
    ]
