# Generated by Django 4.2.7 on 2025-08-11 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0021_merge_20250811_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='vip_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travels.vipcode', verbose_name='Código VIP'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='type',
            field=models.CharField(choices=[('departure', 'Regreso'), ('arrival', 'Llegada')], default='Departure', max_length=100),
        ),
    ]
