# Generated by Django 4.2.7 on 2025-08-11 20:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0022_alter_sale_vip_code_alter_transfer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='stripe_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Código de Venta'),
        ),
    ]
