# Generated by Django 4.2.7 on 2025-08-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0023_sale_stripe_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total'),
            preserve_default=False,
        ),
    ]
