# Generated by Django 4.2.7 on 2025-08-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0024_sale_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Pagado'),
        ),
    ]
