# Generated by Django 4.2.7 on 2025-08-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0025_sale_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.FloatField(verbose_name='Total'),
        ),
    ]
