# Generated by Django 4.2.7 on 2025-08-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0026_alter_sale_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='price',
            field=models.FloatField(verbose_name='Precio'),
        ),
    ]
