# Generated by Django 4.2.7 on 2025-08-12 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0021_delete_saledetail'),
        ('travels', '0027_alter_pricing_price'),
    ]

    operations = [
    ]
