# Generated by Django 4.2.7 on 2025-08-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0028_merge_0021_delete_saledetail_0027_alter_pricing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='type',
            field=models.CharField(choices=[('departure', 'Regreso'), ('arrival', 'Llegada')], default='Departure', max_length=100, verbose_name='Tipo'),
        ),
    ]
