# Generated by Django 4.2.7 on 2025-08-12 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0029_alter_transfer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='location',
        ),
        migrations.AddField(
            model_name='sale',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travels.location', verbose_name='Ubicación'),
            preserve_default=False,
        ),
    ]
