# Generated by Django 4.2.7 on 2025-08-12 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0030_remove_transfer_location_sale_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing',
            old_name='transfer_type',
            new_name='service_type',
        ),
    ]
