# Generated by Django 4.2.7 on 2025-08-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0031_rename_transfer_type_pricing_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
    ]
