# Generated by Django 4.2.7 on 2025-08-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0032_alter_transfer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Detalles adicionales'),
        ),
    ]
