# Generated by Django 4.2.7 on 2025-11-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0035_alter_client_last_name_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='passengers',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pasajeros'),
        ),
    ]
