# Generated by Django 4.2.7 on 2025-11-12 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0036_alter_sale_passengers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='vip_code',
        ),
    ]
