# Generated by Django 4.2.7 on 2025-11-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0037_remove_sale_vip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='passengers',
            field=models.IntegerField(default=0, verbose_name='Pasajeros'),
        ),
    ]
