# Generated by Django 4.2.7 on 2026-09-03 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0038_vehicle_passengers'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='vip_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='travels.vipcode', verbose_name='Código VIP'),
        ),
    ]
